# Site
repository: BellWin98/BellWin98.github.io
favicon: images/profilePic.jpeg

# Content configuration version
version: 2

# Personal info
name: 한종승
title: 서버 백엔드 엔지니어
email: bellwin98@gmail.com
website: www.github.com/BellWin98

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username:  BellWin98
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profilePic.jpeg
about_content: | # this will include new lines to allow paragraphs
   소프트웨어 개발 전문 기업에서 Java & Spring / AWS 기반의 서버 백엔드 개발자로 근무하고 있으며, 
   대기업 계열사의 사내 업무 시스템 개발 및 유지보수, 업무 자동화(RPA) 솔루션을 구축하였습니다.
   고객 업무에 대한 명확한 이해로 좋은 서비스를 만들어내는데 노력하고, 새로운 가치 창출을 통해 성장하는 개발자입니다.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: NEATSOFT
        link: neat-soft.com
        sub_title: 백엔드 개발자
        caption: 2024.05 ~ 현재
        quote: >
          연매출 15억의 중소 기업용 소프트웨어 개발 전문 기업
        description: | # this will include new lines to allow paragraphs
            - Java, Devon Framework, Mybatis, JSP, Uipath Studio(RPA) 환경에서의 개발 경험
            - 자이씨앤에이 사외발송메일 자동 모니터링 시스템 아키텍처 설계 및 구축
            - 자이씨앤에이 사내 시스템 문서 품의상신 전 검토 기능 개발
            - 자이 GPT 데이터 학습을 위한 게시판 수집 RPA 신규 개발
            - 건설현장 공사 데이터 키스콘에 자동 통보하는 RPA 신규 개발
            - 운영 중인 30개 RPA 모니터링 및 유지보수

      - layout: left
        title: 상명대학교
        link: https://seng.smu.ac.kr/coneng/index.do
        sub_title: 융합공과대학교학팀 교직원
        caption: 2023.07 ~ 2023.11
        description: |
            - 융합전자공학전공 졸업 전시회 개최 (전시회 기획, 예산 편성, 대외 홍보)
            - 학부 및 대학원 행정 업무

      - layout: left
        title: 육군본부 제1보병사단 정보통신대대 군수과
        sub_title: 군수과장
        caption: 2022.07 ~ 2023.07
        description: |
            - BTL(병영막사 신축사업)의 공사 관리감독관 임무
            - 부대 내 노후 시설 12곳 중 9곳(75%) 보수 공사
            - 부대 내 노후 및 방치 장비 85% 신규 교체
            - 동원훈련 유공표창 수여

      - layout: left
        title: 육군본부 제1보병사단 정보통신대대 지원2중대
        sub_title: 통신소대장
        caption: 2021.06 ~ 2023.06
        description: |
            - 1사단 국방망 및 전술망 네트워크 구축 및 유지 관리
            - 통신 소대 전술통신체계 및 네트워크 주특기 교육
            - 성과 심의 A등급
  
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 핀업 (프라이빗 맛집 공유 서비스)
        link: https://github.com/TEAM-PIN-UP/BE-PIN-UP
        sub_title: 백엔드 개발
        caption: 2024.09 ~ 현재
        description: | # this will include new lines to allow paragraphs
          - 담당: 백엔드 리드
          - 역할
            - 서비스 아키텍처 및 도메인 설계
            - Spring Boot, JPA, QueryDSL 기반 API 개발
            - 특정 가게에서 친구 맺은 유저의 리뷰 및 별점 조회 시 QueryDSL 사용하여 복잡한 로직 구현 
            - 카카오맵 API 활용하여 전국 음식점, 카페 데이터 수집
            - 소셜(구글) 로그인 연동 및 JWT로 Access/Refresh Token 발급
            - Github Actions, Docker Registry, Docker-Compose 활용한 배포 자동화
            - AWS(EC2, RDS, S3, ELB) 활용한 서버 구축 및 HTTPS 적용
            - Swagger (OAS 3), Postman을 이용한 API 문서화

  - title: Skills # Title for the section
    quote: >
      현재 업무에 사용 중이거나, 사용했던 기술입니다.  
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Backend
        description: |
          - Java
          - Spring Boot, Spring MVC, Spring Data JPA, MyBatis, Redis, JSP
          - QueryDSL, Hibernate
          - Gradle
          
      - layout: left
        title: DevOps
        description: |
          - MariaDB, Oracle
          - Github Actions
          - EC2, RDS(MariaDB), S3, AWS ELB
          - Docker, Docker-Compose

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 한화시스템 BEYOND SW캠프 3기
        caption: 2023.11 ~ 2024.04
        description: | 
          - Spring Framework, AWS, Vue.js를 활용한 팀 프로젝트 2회 리딩
          - 성과: 총 3회 반 평가 중 2회 1위 달성

      - layout: left
        title: 상명대학교 서울캠퍼스
        caption: 2017 - 2021
        sub_title: 글로벌경영학과(본전공) / 휴먼지능정보공학전공(복수전공)
        description: | 
          - GPA: 3.81/4.5
          - 수상내역: 캡스톤디자인 경진대회 장려상 (딥러닝 & 라즈베리파이 활용한 인공지능 쓰레기통 제작)
          - 대외활동: ROTC 59기, 소리마을(중앙밴드동아리) 드러머, 시애틀 산업시찰단, 라오스 해외봉사, 필리핀 어학연수, 외국인 튜터링

# Footer
# footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
