# Site
repository: BellWin98/BellWin98.github.io
favicon: images/profilePic.jpeg

# Content configuration version
version: 2

# Personal info
name: 한종승
title: 서버 백엔드 엔지니어
email: bellwin98@gmail.com
website: www.github.com/BellWin98

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  BellWin98

# About Section
about_profile_image: images/profilePic.jpeg
about_content: | 
   소프트웨어 개발 전문 기업에서 Java & Spring / AWS 기반의 서버 백엔드 개발자로 근무하고 있으며, 
   대기업 계열사의 사내 업무 시스템 개발 및 유지보수, 업무 자동화(RPA) 솔루션을 구축하였습니다. <br/><br/>
   고객 업무에 대한 명확한 이해로 좋은 서비스를 만들어내는데 노력하고, 새로운 가치 창출을 통해 성장하는 개발자입니다.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: NEATSOFT
        link: neat-soft.com
        sub_title: 백엔드 개발자
        caption: 2024.05 ~ 현재
        quote: >
          연매출 15억 규모 중소기업 대상 소프트웨어 개발 전문 회사
        description: |
          - Java, Devon Framework, MyBatis, JSP, UiPath(RPA) 등 다양한 기술 스택을 활용한 개발 경험 
          - **사외발송메일 자동 모니터링 시스템** 아키텍처 설계 및 구축
            → 기존 수작업으로 하던 모니터링 대비 보안 위반 메일 탐지 시간 96% 단축 (30분 -> 1분)
          - **사내 결재 문서 품의 상신 전 검토 기능** 개발 
            → 품의 상신 후 문서 재작성율 80% 감소
          - **자이 GPT 게시판 데이터 수집 RPA** 개발 
            → GPT 모델 학습 데이터 자동 수집 환경 구축
          - **건설공사 데이터 키스콘 자동통보 RPA** 개발 
            → 공사계약 내용을 키스콘에 수동으로 통보하는 시간 83% 단축 (3시간 -> 30분) 
            → 통보 성공율 125% 증가 (40% -> 90%)
          - 현재 운영 중인 **30개의 RPA 모니터링 및 유지보수**

      - layout: left
        title: 상명대학교
        link: https://seng.smu.ac.kr/coneng/index.do
        sub_title: 융합공과대학교학팀 교직원
        caption: 2023.07 ~ 2023.11
        description: |
          - **융합전자공학전공 졸업 전시회** 기획·운영 (예산 편성, 대외 홍보 포함) 
            → 전시회 만족도 조사 결과 “매우 만족” 85% 달성
          - 학부 및 대학원 행정업무 전반

      - layout: left
        title: 육군본부 제1보병사단 정보통신대대 군수과
        sub_title: 군수과장
        caption: 2022.07 ~ 2023.07
        description: |
          - **BTL(병영막사 신축사업)** 공사 관리감독관 
            → 배정 예산 내 100% 공사 완료, 군 시설 개선도 향상
          - 노후 시설 12곳 중 9곳(75%) 보수 공사 완료
          - 노후·방치 통신 장비 85% 신규 교체 
            → 통신망 개통 속도 70%, 장비 활용률 90% 향상
          - 동원훈련 유공표창 수여

      - layout: left
        title: 육군본부 제1보병사단 정보통신대대 지원2중대
        sub_title: 통신소대장
        caption: 2021.06 ~ 2023.06
        description: |
          - 1사단 국방망·전술망 네트워크 인프라 구축 및 유지관리 총괄
          - 통신소대 주특기(전술통신·네트워크) 교육 기획·진행  
          - 성과 심의 **A등급** 획득

  - title: Projects
    layout: list
    content:
      - layout: left
        title: 핀업 (프라이빗 맛집 공유 서비스)
        link: https://github.com/TEAM-PIN-UP/BE-PIN-UP
        sub_title: 백엔드 리드
        caption: 2024.09 ~ 현재
        description: |
          - **인원**: 9명 (기획 2, 마케팅 1, 디자인 1, FE 3, BE 2)  
          - **역할 및 성과**  
            - 서비스 아키텍처 및 도메인 설계 주도  
            - Spring Boot, JPA, QueryDSL 기반 API 개발  
            - 카카오맵 API 연동하여 전국 음식점·카페 데이터 수집  
            - QueryDSL 활용하여 **특정 가게에서 친구 맺은 유저의 리뷰·별점 조회 성능 30%** 개선
            - 소셜(구글) 로그인 및 JWT(Access/Refresh Token) 기반 인증 API 개발  
            - **배포 자동화**: GitHub Actions + Docker Registry + Docker-Compose 활용
            - AWS EC2, RDS, S3, ELB로 서버 구축 및 HTTPS 적용  
            - 전역 에러 핸들링 구축
            - Spring AOP 활용한 Controller, Service단 로깅 적용 
            - Swagger 3, Postman 활용한 API 문서화  
            
  - title: Skills
    layout: list
    content:
      - layout: left
        title: Backend
        description: |
          - Java, JSP
          - Spring Boot, Spring MVC, Spring AOP, Spring Security
          - Spring Data JPA, MyBatis
          - QueryDSL, JWT, OAuth2
          - Gradle, Swagger 3, Postman
          
      - layout: left
        title: DevOps
        description: |
          - MariaDB, Oracle, Redis
          - GitHub Actions
          - AWS(EC2, RDS, S3, ELB)
          - Docker, Docker-Compose, Docker Registry

  - title: ETC
    layout: list
    content:
      - layout: left
        title: 자격증
        description: |
          - 정보처리기사  
            - 취득일: 2023.06.09  
            - 자격번호: 23201010765B  
          - SQL개발자(SQLD)  
            - 취득일: 2023.07.07  
            - 자격번호: SQLD-049010352  
          - 토익스피킹 IH  
            - 응시일: 2023.09.17  
            - 자격번호: 101607

  - title: Education
    layout: list
    content:
      - layout: left
        title: 한화시스템 BEYOND SW캠프 3기
        caption: 2023.11 ~ 2024.04
        description: | 
          - Spring Framework, AWS, Vue.js를 활용한 팀 프로젝트 2회 리딩 
            → 서비스 기획 ~ 배포까지 전 과정 주도
          - 총 3회 반 평가 중 **2회 1위** 달성

      - layout: left
        title: 상명대학교 서울캠퍼스
        caption: 2017 - 2021
        sub_title: 글로벌경영학과(본전공) / 휴먼지능정보공학전공(복수전공)
        description: | 
          - GPA: 3.81/4.5
          - **캡스톤디자인 경진대회 장려상** 수상  
            (딥러닝 & 라즈베리파이 활용 인공지능 쓰레기통 제작 프로젝트)
          - 대외활동: ROTC 59기, 소리마을(중앙 밴드) 드러머, 시애틀 산업시찰단, 라오스 해외봉사, 필리핀 어학연수, 외국인 튜터링

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
